# Generated by Django 2.2.1 on 2019-05-30 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='imagem',
            field=models.FileField(blank=True, null=True, upload_to='media/%Y/%m/%d/'),
        ),
    ]
