# Generated by Django 2.2.3 on 2019-07-02 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_cliente_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='clientes'),
        ),
    ]
